apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-d3qq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-d3qq@sha256:a78b68a196be0e359c7b8071cc66819e37994f4bdf7cb8fa7ae619b2f15e69b3
        name: my-nodejs
        resources: {}
status: {}
